'use client';

import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'english' | 'spanish' | 'french' | 'german' | 'japanese' | 'chinese' | 'indonesian';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translations object
const translations: Record<Language, Record<string, string>> = {
  english: {
    'welcome': 'Welcome',
    'dashboard': 'Dashboard',
    'users': 'Users',
    'settings': 'Settings',
    'profile': 'Profile',
    'permissions': 'Permissions',
    'role_permissions': 'Role Permissions',
    'admin': 'Admin',
    'sign_out': 'Sign Out',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'save': 'Save',
    'cancel': 'Cancel',
    'success': 'Success',
    'error': 'Error',
    'loading': 'Loading...',
    'save_settings': 'Save Settings',
    'settings_saved': 'Settings saved successfully!',
    'settings_error': 'Failed to save settings',
    'email_notifications': 'Email Notifications',
    'receive_notifications': 'Receive email notifications',
    'push_notifications': 'Push Notifications',
    'receive_push_notifications': 'Receive push notifications',
    'sms_notifications': 'SMS Notifications',
    'receive_sms_notifications': 'Receive SMS notifications',
    'marketing_emails': 'Marketing Emails',
    'receive_marketing_emails': 'Receive marketing emails',
    'appearance_settings': 'Appearance Settings',
    'notification_settings': 'Notification Settings',
    'manage_preferences': 'Manage your application preferences',
    'use_dark_theme': 'Use dark theme for the application',
    'receive_email_notifications': 'Receive email notifications for important updates',
    'application_settings': 'Application Settings',
    'application_title': 'Application Title',
    'application_title_description': 'This will change the title displayed in the browser tab and throughout the application.',
    'page_dashboard': 'Dashboard',
    'page_users': 'Users',
    'page_admin': 'Admin',
    'page_settings': 'Settings',
    'page_login': 'Login',
    'page_database': 'Database Management',
    'logo_settings': 'Logo Settings',
    'custom_logo': 'Custom Logo',
    'enable_custom_logo': 'Enable Custom Logo',
    'logo_url': 'Logo URL',
    'logo_url_placeholder': 'Enter logo URL (e.g., https://example.com/logo.png)',
    'logo_url_description': 'Enter a URL to your custom logo image. Supported formats: PNG, JPG, SVG.',
    'reset_to_default': 'Reset to Default',
    'logo_preview': 'Logo Preview',
    // Admin page translations
    'admin_dashboard': 'Admin Dashboard',
    'admin_dashboard_description': 'Manage system settings and user permissions',
    'user_created': 'User created',
    'permission_updated': 'Permission updated',
    'user_deleted': 'User deleted',
    'database_management_description': 'Manage database connections and schema',
    'manage_database': 'Manage Database',
    'user_management': 'User Management',
    'user_management_description': 'Add, edit, and manage user accounts',
    'permissions_description': 'Configure user roles and permissions',
    'system_settings': 'System Settings',
    'system_settings_description': 'Configure application settings',
    'coming_soon': 'Coming Soon',
    'total_users': 'Total Users',
    'active_users': 'Active Users',
    'inactive_users': 'Inactive Users',
    'recent_admin_actions': 'Recent Admin Actions',
    'action': 'Action',
    'user': 'User',
    'timestamp': 'Timestamp',
    // Database page translations
    'access_denied': 'Access Denied',
    'login_required': 'You need to be logged in to access this page.',
    'sign_in': 'Sign In',
    'database_management_desc': 'Manage PostgreSQL database connection and schema',
    'database_status': 'Database Status',
    'checking_database_status': 'Checking database status...',
    'database_connected': 'Database Connected',
    'database_error': 'Database Error',
    'connection_details': 'Connection Details',
    'last_check': 'Last Check',
    'tables': 'Tables',
    'error_details': 'Error Details',
    'no_status_available': 'No Status Available',
    'unable_retrieve_status': 'Unable to retrieve database status',
    'checking': 'Checking...',
    'refresh_status': 'Refresh Status',
    'initializing': 'Initializing...',
    'initialize_database': 'Initialize Database',
    'database_configuration': 'Database Configuration',
    'environment_variables': 'Environment Variables',
    'configuration_note': 'Configuration Note',
    'database_config_note': 'Database configuration is managed through environment variables. Make sure to set the correct values in your .env file.',
    'quick_actions': 'Quick Actions',
    'database_initialized_success': 'Database initialized successfully!',
    'failed_initialize_database': 'Failed to initialize database'
  },
  spanish: {
    'welcome': 'Bienvenido',
    'dashboard': 'Panel de Control',
    'users': 'Usuarios',
    'settings': 'Configuración',
    'profile': 'Perfil',
    'permissions': 'Permisos',
    'role_permissions': 'Permisos de Rol',
    'admin': 'Administrador',
    'sign_out': 'Cerrar Sesión',
    'dark_mode': 'Modo Oscuro',
    'language': 'Idioma',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'success': 'Éxito',
    'error': 'Error',
    'loading': 'Cargando...',
    'save_settings': 'Guardar Configuración',
    'settings_saved': '¡Configuración guardada exitosamente!',
    'settings_error': 'Error al guardar la configuración',
    'email_notifications': 'Notificaciones por Email',
    'receive_notifications': 'Recibir notificaciones por email',
    'push_notifications': 'Notificaciones Push',
    'receive_push_notifications': 'Recibir notificaciones push',
    'sms_notifications': 'Notificaciones SMS',
    'receive_sms_notifications': 'Recibir notificaciones SMS',
    'marketing_emails': 'Emails de Marketing',
    'receive_marketing_emails': 'Recibir emails de marketing',
    'appearance_settings': 'Configuración de Apariencia',
    'notification_settings': 'Configuración de Notificaciones',
    'manage_preferences': 'Gestiona las preferencias de tu aplicación',
    'use_dark_theme': 'Usar tema oscuro para la aplicación',
    'receive_email_notifications': 'Recibir notificaciones por email para actualizaciones importantes',
    'application_settings': 'Configuración de Aplicación',
    'application_title': 'Título de la Aplicación',
    'application_title_description': 'Esto cambiará el título mostrado en la pestaña del navegador y en toda la aplicación.',
    'page_dashboard': 'Panel de Control',
    'page_users': 'Usuarios',
    'page_admin': 'Administrador',
    'page_settings': 'Configuración',
    'page_login': 'Iniciar Sesión',
    'page_database': 'Gestión de Base de Datos',
    'logo_settings': 'Configuración de Logo',
    'custom_logo': 'Logo Personalizado',
    'enable_custom_logo': 'Habilitar Logo Personalizado',
    'logo_url': 'URL del Logo',
    'logo_url_placeholder': 'Ingrese URL del logo (ej: https://example.com/logo.png)',
    'logo_url_description': 'Ingrese una URL a su imagen de logo personalizada. Formatos soportados: PNG, JPG, SVG.',
    'reset_to_default': 'Restablecer por Defecto',
    'logo_preview': 'Vista Previa del Logo',
    // Admin page translations
    'admin_dashboard': 'Panel de Administración',
    'admin_dashboard_description': 'Gestionar configuraciones del sistema y permisos de usuario',
    'user_created': 'Usuario creado',
    'permission_updated': 'Permiso actualizado',
    'user_deleted': 'Usuario eliminado',
    'database_management_description': 'Gestionar conexiones de base de datos y esquema',
    'manage_database': 'Gestionar Base de Datos',
    'user_management': 'Gestión de Usuarios',
    'user_management_description': 'Agregar, editar y gestionar cuentas de usuario',
    'permissions_description': 'Configurar roles y permisos de usuario',
    'system_settings': 'Configuraciones del Sistema',
    'system_settings_description': 'Configurar ajustes de la aplicación',
    'coming_soon': 'Próximamente',
    'total_users': 'Total de Usuarios',
    'active_users': 'Usuarios Activos',
    'inactive_users': 'Usuarios Inactivos',
    'recent_admin_actions': 'Acciones Administrativas Recientes',
    'action': 'Acción',
    'user': 'Usuario',
    'timestamp': 'Marca de Tiempo',
    // Database page translations
    'access_denied': 'Acceso Denegado',
    'login_required': 'Necesitas iniciar sesión para acceder a esta página.',
    'sign_in': 'Iniciar Sesión',
    'database_management_desc': 'Gestionar conexión y esquema de base de datos PostgreSQL',
    'database_status': 'Estado de la Base de Datos',
    'checking_database_status': 'Verificando estado de la base de datos...',
    'database_connected': 'Base de Datos Conectada',
    'database_error': 'Error de Base de Datos',
    'connection_details': 'Detalles de Conexión',
    'last_check': 'Última Verificación',
    'tables': 'Tablas',
    'error_details': 'Detalles del Error',
    'no_status_available': 'Sin Estado Disponible',
    'unable_retrieve_status': 'No se puede recuperar el estado de la base de datos',
    'checking': 'Verificando...',
    'refresh_status': 'Actualizar Estado',
    'initializing': 'Inicializando...',
    'initialize_database': 'Inicializar Base de Datos',
    'database_configuration': 'Configuración de Base de Datos',
    'environment_variables': 'Variables de Entorno',
    'configuration_note': 'Nota de Configuración',
    'database_config_note': 'La configuración de la base de datos se gestiona a través de variables de entorno. Asegúrese de establecer los valores correctos en su archivo .env.',
    'quick_actions': 'Acciones Rápidas',
    'database_initialized_success': '¡Base de datos inicializada exitosamente!',
    'failed_initialize_database': 'Error al inicializar la base de datos'
  },
  french: {
    'welcome': 'Bienvenue',
    'dashboard': 'Tableau de Bord',
    'users': 'Utilisateurs',
    'settings': 'Paramètres',
    'profile': 'Profil',
    'permissions': 'Permissions',
    'role_permissions': 'Permissions de Rôle',
    'admin': 'Administrateur',
    'sign_out': 'Se Déconnecter',
    'dark_mode': 'Mode Sombre',
    'language': 'Langue',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'success': 'Succès',
    'error': 'Erreur',
    'loading': 'Chargement...',
    'save_settings': 'Sauvegarder les Paramètres',
    'settings_saved': 'Paramètres sauvegardés avec succès!',
    'settings_error': 'Échec de la sauvegarde des paramètres',
    'email_notifications': 'Notifications Email',
    'receive_notifications': 'Recevoir des notifications par email',
    'push_notifications': 'Notifications Push',
    'receive_push_notifications': 'Recevoir des notifications push',
    'sms_notifications': 'Notifications SMS',
    'receive_sms_notifications': 'Recevoir des notifications SMS',
    'marketing_emails': 'Emails Marketing',
    'receive_marketing_emails': 'Recevoir des emails marketing',
    'appearance_settings': 'Paramètres d\'Apparence',
    'notification_settings': 'Paramètres de Notification',
    'manage_preferences': 'Gérez vos préférences d\'application',
    'use_dark_theme': 'Utiliser le thème sombre pour l\'application',
    'receive_email_notifications': 'Recevoir des notifications email pour les mises à jour importantes',
    'application_settings': 'Paramètres d\'Application',
    'application_title': 'Titre de l\'Application',
    'application_title_description': 'Cela changera le titre affiché dans l\'onglet du navigateur et dans toute l\'application.',
    'page_dashboard': 'Tableau de Bord',
    'page_users': 'Utilisateurs',
    'page_admin': 'Administrateur',
    'page_settings': 'Paramètres',
    'page_login': 'Connexion',
    'page_database': 'Gestion de Base de Données',
    'logo_settings': 'Paramètres du Logo',
    'custom_logo': 'Logo Personnalisé',
    'enable_custom_logo': 'Activer le Logo Personnalisé',
    'logo_url': 'URL du Logo',
    'logo_url_placeholder': 'Entrez l\'URL du logo (ex: https://example.com/logo.png)',
    'logo_url_description': 'Entrez une URL vers votre image de logo personnalisée. Formats supportés: PNG, JPG, SVG.',
    'reset_to_default': 'Rétablir par Défaut',
    'logo_preview': 'Aperçu du Logo'
  },
  german: {
    'welcome': 'Willkommen',
    'dashboard': 'Dashboard',
    'users': 'Benutzer',
    'settings': 'Einstellungen',
    'profile': 'Profil',
    'permissions': 'Berechtigungen',
    'role_permissions': 'Rollenberechtigungen',
    'admin': 'Administrator',
    'sign_out': 'Abmelden',
    'dark_mode': 'Dunkler Modus',
    'language': 'Sprache',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'success': 'Erfolg',
    'error': 'Fehler',
    'loading': 'Laden...',
    'save_settings': 'Einstellungen Speichern',
    'settings_saved': 'Einstellungen erfolgreich gespeichert!',
    'settings_error': 'Fehler beim Speichern der Einstellungen',
    'email_notifications': 'E-Mail-Benachrichtigungen',
    'receive_notifications': 'E-Mail-Benachrichtigungen erhalten',
    'push_notifications': 'Push-Benachrichtigungen',
    'receive_push_notifications': 'Push-Benachrichtigungen erhalten',
    'sms_notifications': 'SMS-Benachrichtigungen',
    'receive_sms_notifications': 'SMS-Benachrichtigungen erhalten',
    'marketing_emails': 'Marketing-E-Mails',
    'receive_marketing_emails': 'Marketing-E-Mails erhalten',
    'appearance_settings': 'Erscheinungseinstellungen',
    'notification_settings': 'Benachrichtigungseinstellungen',
    'manage_preferences': 'Verwalten Sie Ihre Anwendungseinstellungen',
    'use_dark_theme': 'Dunkles Design für die Anwendung verwenden',
    'receive_email_notifications': 'E-Mail-Benachrichtigungen für wichtige Updates erhalten',
    'application_settings': 'Anwendungseinstellungen',
    'application_title': 'Anwendungstitel',
    'application_title_description': 'Dies ändert den Titel, der im Browser-Tab und in der gesamten Anwendung angezeigt wird.',
    'page_dashboard': 'Dashboard',
    'page_users': 'Benutzer',
    'page_admin': 'Administrator',
    'page_settings': 'Einstellungen',
    'page_login': 'Anmelden',
    'page_database': 'Datenbankverwaltung',
    'logo_settings': 'Logo-Einstellungen',
    'custom_logo': 'Benutzerdefiniertes Logo',
    'enable_custom_logo': 'Benutzerdefiniertes Logo aktivieren',
    'logo_url': 'Logo-URL',
    'logo_url_placeholder': 'Logo-URL eingeben (z.B.: https://example.com/logo.png)',
    'logo_url_description': 'Geben Sie eine URL zu Ihrem benutzerdefinierten Logo-Bild ein. Unterstützte Formate: PNG, JPG, SVG.',
    'reset_to_default': 'Auf Standard zurücksetzen',
    'logo_preview': 'Logo-Vorschau'
  },
  japanese: {
    'welcome': 'ようこそ',
    'dashboard': 'ダッシュボード',
    'users': 'ユーザー',
    'settings': '設定',
    'profile': 'プロフィール',
    'permissions': '権限',
    'role_permissions': 'ロール権限',
    'admin': '管理者',
    'sign_out': 'サインアウト',
    'dark_mode': 'ダークモード',
    'language': '言語',
    'save': '保存',
    'cancel': 'キャンセル',
    'success': '成功',
    'error': 'エラー',
    'loading': '読み込み中...',
    'save_settings': '設定を保存',
    'settings_saved': '設定が正常に保存されました！',
    'settings_error': '設定の保存に失敗しました',
    'email_notifications': 'メール通知',
    'receive_notifications': 'メール通知を受信する',
    'push_notifications': 'プッシュ通知',
    'receive_push_notifications': 'プッシュ通知を受信する',
    'sms_notifications': 'SMS通知',
    'receive_sms_notifications': 'SMS通知を受信する',
    'marketing_emails': 'マーケティングメール',
    'receive_marketing_emails': 'マーケティングメールを受信する',
    'appearance_settings': '外観設定',
    'notification_settings': '通知設定',
    'manage_preferences': 'アプリケーションの設定を管理',
    'use_dark_theme': 'アプリケーションにダークテーマを使用',
    'receive_email_notifications': '重要な更新のメール通知を受信',
    'application_settings': 'アプリケーション設定',
    'application_title': 'アプリケーションタイトル',
    'application_title_description': 'これにより、ブラウザタブとアプリケーション全体に表示されるタイトルが変更されます。',
    'page_dashboard': 'ダッシュボード',
    'page_users': 'ユーザー',
    'page_admin': '管理者',
    'page_settings': '設定',
    'page_login': 'ログイン',
    'page_database': 'データベース管理',
    'logo_settings': 'ロゴ設定',
    'custom_logo': 'カスタムロゴ',
    'enable_custom_logo': 'カスタムロゴを有効にする',
    'logo_url': 'ロゴURL',
    'logo_url_placeholder': 'ロゴURLを入力 (例: https://example.com/logo.png)',
    'logo_url_description': 'カスタムロゴ画像のURLを入力してください。対応形式: PNG、JPG、SVG。',
    'reset_to_default': 'デフォルトにリセット',
    'logo_preview': 'ロゴプレビュー'
  },
  chinese: {
    'welcome': '欢迎',
    'dashboard': '仪表板',
    'users': '用户',
    'settings': '设置',
    'profile': '个人资料',
    'permissions': '权限',
    'role_permissions': '角色权限',
    'admin': '管理员',
    'sign_out': '退出登录',
    'dark_mode': '深色模式',
    'language': '语言',
    'save': '保存',
    'cancel': '取消',
    'success': '成功',
    'error': '错误',
    'loading': '加载中...',
    'save_settings': '保存设置',
    'settings_saved': '设置保存成功！',
    'settings_error': '保存设置失败',
    'email_notifications': '邮件通知',
    'receive_notifications': '接收邮件通知',
    'push_notifications': '推送通知',
    'receive_push_notifications': '接收推送通知',
    'sms_notifications': '短信通知',
    'receive_sms_notifications': '接收短信通知',
    'marketing_emails': '营销邮件',
    'receive_marketing_emails': '接收营销邮件',
    'appearance_settings': '外观设置',
    'notification_settings': '通知设置',
    'manage_preferences': '管理您的应用程序偏好设置',
    'use_dark_theme': '为应用程序使用深色主题',
    'receive_email_notifications': '接收重要更新的邮件通知',
    'application_settings': '应用程序设置',
    'application_title': '应用程序标题',
    'application_title_description': '这将更改在浏览器标签页和整个应用程序中显示的标题。',
    'page_dashboard': '仪表板',
    'page_users': '用户',
    'page_admin': '管理员',
    'page_settings': '设置',
    'page_login': '登录',
    'page_database': '数据库管理',
    'logo_settings': '徽标设置',
    'custom_logo': '自定义徽标',
    'enable_custom_logo': '启用自定义徽标',
    'logo_url': '徽标URL',
    'logo_url_placeholder': '输入徽标URL (例如: https://example.com/logo.png)',
    'logo_url_description': '输入您的自定义徽标图像URL。支持的格式：PNG、JPG、SVG。',
    'reset_to_default': '重置为默认',
    'logo_preview': '徽标预览'
  },
  indonesian: {
    'welcome': 'Selamat datang',
    'dashboard': 'Dasbor',
    'users': 'Pengguna',
    'settings': 'Pengaturan',
    'profile': 'Profil',
    'permissions': 'Izin',
    'role_permissions': 'Izin Peran',
    'admin': 'Admin',
    'sign_out': 'Keluar',
    'dark_mode': 'Mode Gelap',
    'language': 'Bahasa',
    'save': 'Simpan',
    'cancel': 'Batal',
    'success': 'Berhasil',
    'error': 'Error',
    'loading': 'Memuat...',
    'save_settings': 'Simpan Pengaturan',
    'settings_saved': 'Pengaturan berhasil disimpan!',
    'settings_error': 'Gagal menyimpan pengaturan',
    'email_notifications': 'Notifikasi Email',
    'receive_notifications': 'Terima notifikasi email',
    'push_notifications': 'Notifikasi Push',
    'receive_push_notifications': 'Terima notifikasi push',
    'sms_notifications': 'Notifikasi SMS',
    'receive_sms_notifications': 'Terima notifikasi SMS',
    'marketing_emails': 'Email Marketing',
    'receive_marketing_emails': 'Terima email marketing',
    'appearance_settings': 'Pengaturan Tampilan',
    'notification_settings': 'Pengaturan Notifikasi',
    'manage_preferences': 'Kelola preferensi aplikasi Anda',
    'use_dark_theme': 'Gunakan tema gelap untuk aplikasi',
    'receive_email_notifications': 'Terima notifikasi email untuk pembaruan penting',
    'application_settings': 'Pengaturan Aplikasi',
    'application_title': 'Judul Aplikasi',
    'application_title_description': 'Ini akan mengubah judul yang ditampilkan di tab browser dan di seluruh aplikasi.',
    'page_dashboard': 'Dashboard',
    'page_users': 'Pengguna',
    'page_admin': 'Admin',
    'page_settings': 'Pengaturan',
    'page_login': 'Masuk',
    'page_database': 'Manajemen Database',
    'logo_settings': 'Pengaturan Logo',
    'custom_logo': 'Logo Kustom',
    'enable_custom_logo': 'Aktifkan Logo Kustom',
    'logo_url': 'URL Logo',
    'logo_url_placeholder': 'Masukkan URL logo (contoh: https://example.com/logo.png)',
    'logo_url_description': 'Masukkan URL ke gambar logo kustom Anda. Format yang didukung: PNG, JPG, SVG.',
    'reset_to_default': 'Reset ke Default',
    'logo_preview': 'Pratinjau Logo',
    // Admin page translations
    'admin_dashboard': 'Dashboard Admin',
    'admin_dashboard_description': 'Kelola pengaturan sistem dan izin pengguna',
    'user_created': 'Pengguna dibuat',
    'permission_updated': 'Izin diperbarui',
    'user_deleted': 'Pengguna dihapus',
    'database_management_description': 'Kelola koneksi database dan skema',
    'manage_database': 'Kelola Database',
    'user_management': 'Manajemen Pengguna',
    'user_management_description': 'Tambah, edit, dan kelola akun pengguna',
    'permissions_description': 'Konfigurasi peran dan izin pengguna',
    'system_settings': 'Pengaturan Sistem',
    'system_settings_description': 'Konfigurasi pengaturan aplikasi',
    'coming_soon': 'Segera Hadir',
    'total_users': 'Total Pengguna',
    'active_users': 'Pengguna Aktif',
    'inactive_users': 'Pengguna Tidak Aktif',
    'recent_admin_actions': 'Tindakan Admin Terbaru',
    'action': 'Tindakan',
    'user': 'Pengguna',
    'timestamp': 'Waktu',
    // Database page translations
    'access_denied': 'Akses Ditolak',
    'login_required': 'Anda perlu masuk untuk mengakses halaman ini.',
    'sign_in': 'Masuk',
    'database_management_desc': 'Kelola koneksi dan skema database PostgreSQL',
    'database_status': 'Status Database',
    'checking_database_status': 'Memeriksa status database...',
    'database_connected': 'Database Terhubung',
    'database_error': 'Error Database',
    'connection_details': 'Detail Koneksi',
    'last_check': 'Pemeriksaan Terakhir',
    'tables': 'Tabel',
    'error_details': 'Detail Error',
    'no_status_available': 'Tidak Ada Status Tersedia',
    'unable_retrieve_status': 'Tidak dapat mengambil status database',
    'checking': 'Memeriksa...',
    'refresh_status': 'Refresh Status',
    'initializing': 'Menginisialisasi...',
    'initialize_database': 'Inisialisasi Database',
    'database_configuration': 'Konfigurasi Database',
    'environment_variables': 'Variabel Lingkungan',
    'configuration_note': 'Catatan Konfigurasi',
    'database_config_note': 'Konfigurasi database dikelola melalui variabel lingkungan. Pastikan untuk mengatur nilai yang benar di file .env Anda.',
    'quick_actions': 'Tindakan Cepat',
    'database_initialized_success': 'Database berhasil diinisialisasi!',
    'failed_initialize_database': 'Gagal menginisialisasi database'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('english');

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}